apiVersion: v1
kind: Pod
metadata:
  name: sample-hostaliases
spec:
  containers:
    - name: nginx-containers
      image: nginx:1.16
  # /etc/hostsにホストを追記できる
  hostAliases:
  - ip: 8.8.8.8
    hostnames:
      - google-dns
      - google-public-dns