apiVersion: v1
kind: Pod
metadata: 
  name: sample-annotations
  annotations:
    annotation1: val1
    annotation2: "200"
spec:
  containers:
  - name: nginx-containers
    image: nginx:1.16